# Generated by Django 6.0.4 on 2026-04-11 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('grupos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='grupos.grupo')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('makeup', 'Recuperacion'), ('guest', 'Invitado/Traslado')], default='present', max_length=10)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('es_invitado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='asistencia.sesion')),
            ],
            options={
                'unique_together': {('sesion', 'alumno')},
            },
        ),
    ]
