# Generated by Django 6.0.4 on 2026-07-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='contenido',
            field=models.TextField(blank=True),
        ),
    ]
