# Generated by Django 6.0.4 on 2026-09-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_sesion_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('makeup', 'Recuperacion'), ('guest', 'Invitado/Traslado'), ('other', 'Otro')], default='present', max_length=10),
        ),
    ]
