# Generated by Django 6.0.4 on 2026-10-10 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def rellenar_actividad(apps, schema_editor):
    """Los avisos que ya existen: última actividad = cuándo se crearon, y la
    última persona = quien los creó (así no aparecen como "sin leer")."""
    Aviso = apps.get_model("avisos", "Aviso")
    Aviso.objects.update(ultima_actividad=F("created_at"), ultimo_autor=F("creado_por"))


class Migration(migrations.Migration):

    dependencies = [
        ("avisos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aviso",
            name="para_todos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aviso",
            name="ultima_actividad",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="aviso",
            name="ultimo_autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AvisoMensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avisos_mensajes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aviso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="avisos.aviso",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="AvisoLectura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leido_hasta", models.DateTimeField()),
                (
                    "aviso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturas",
                        to="avisos.aviso",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avisos_lecturas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("aviso", "user")},
            },
        ),
        migrations.RunPython(rellenar_actividad, migrations.RunPython.noop),
    ]
