# Generated by Django 6.0.4 on 2026-05-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoempresa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='facturacion',
            field=models.CharField(blank=True, choices=[('global', 'Factura global mensual'), ('por_alumno', 'Factura por alumno'), ('fundae', 'FUNDAE'), ('mixta', 'Mixta')], default='global', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
