# Generated by Django 6.0.4 on 2026-05-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaccion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='interaccion',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('llamada', 'Llamada'), ('email', 'Email'), ('reunion', 'Reunión'), ('en_persona', 'En persona'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='etapa',
            field=models.CharField(choices=[('nueva_consulta', 'Nueva consulta'), ('pendiente_llamar', 'Pendiente de llamar'), ('en_conversacion', 'En conversación'), ('clase_prueba', 'Clase de prueba programada'), ('matriculado', 'Matriculado'), ('frio', 'Frío'), ('archivado', 'Archivado')], default='nueva_consulta', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='objetivo',
            field=models.CharField(choices=[('cambridge', 'Cambridge'), ('ib', 'IB'), ('general', 'General'), ('conversacion', 'Conversación'), ('otro', 'Otro')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='origen',
            field=models.CharField(choices=[('telefono', 'Teléfono'), ('boca_a_boca', 'Boca a boca'), ('en_persona', 'En persona'), ('test_nivel', 'Test de nivel'), ('instagram', 'Instagram'), ('email', 'Email'), ('otro', 'Otro')], default='telefono', max_length=20),
        ),
    ]
