# Generated by Django 6.0.4 on 2026-05-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_interaccion_id_alter_interaccion_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
