# Generated by Django 6.0.4 on 2026-07-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_lead_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='objetivo',
            field=models.CharField(choices=[('general', 'General'), ('cambridge', 'Cambridge'), ('ib', 'IB'), ('adultos', 'Adultos')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='origen',
            field=models.CharField(choices=[('telefono', 'Teléfono'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('recomendacion', 'Recomendación'), ('web', 'Web')], default='telefono', max_length=20),
        ),
    ]
