# Generated by Django 6.0.4 on 2026-07-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_lead_objetivo_alter_lead_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='es_adulto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='pagador_es_alumno',
            field=models.BooleanField(default=False, help_text='Si es_adulto=True y el alumno paga por si mismo, autocompleta el pagador con sus propios datos al matricular.'),
        ),
    ]
