# Generated by Django 6.0.4 on 2026-07-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_lead_es_adulto_lead_pagador_es_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
