# Generated by Django 6.0.4 on 2026-04-11 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('grupos', '0001_initial'),
        ('pagadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('mensualidad', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('extras', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('parcial', 'Pago parcial')], default='pendiente', max_length=20)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('num_doc', models.CharField(blank=True, max_length=30)),
                ('serie_id', models.CharField(blank=True, max_length=10)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='alumnos.alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='grupos.grupo')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pagadores.pagador')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
