# Generated by Django 6.0.4 on 2026-05-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='horas_trabajadas',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Horas trabajadas este mes', max_digits=5),
        ),
    ]
