# Generated by Django 6.0.4 on 2026-06-29 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_add_emisor_and_pago_link'),
        ('pagos', '0002_pago_horas_trabajadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='documentos.emisor'),
        ),
    ]
