# Generated by Django 6.0.4 on 2026-07-04 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_add_emisor_and_pago_link'),
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='tarifas.tarifa'),
        ),
    ]
