# Generated by Django 6.0.4 on 2026-07-04 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_grupo_precio_hora_grupo_tipo_cobro'),
        ('pagos', '0004_pago_tarifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='grupos.grupo'),
        ),
    ]
