# Generated by Django 6.0.4 on 2026-07-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_alter_pago_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='marca',
            field=models.CharField(choices=[('cami_and_co', 'Cami & Co'), ('rangers_academy', 'Rangers Academy')], default='rangers_academy', max_length=20),
        ),
    ]
