# Generated by Django 6.0.4 on 2026-07-05 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alumno_marca'),
        ('pagadores', '0001_initial'),
        ('pagos', '0006_pago_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='concepto_original',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pago',
            name='estado_carga',
            field=models.CharField(choices=[('completo', 'Completo'), ('pendiente_completar', 'Pendiente de completar')], default='completo', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_factura_reservado',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pago',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pagador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pagadores.pagador'),
        ),
    ]
