# Generated by Django 6.0.4 on 2026-07-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_pago_carga_taxfix'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='concepto_libre',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
