# Generated by Django 6.0.4 on 2026-07-05 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alumno_marca'),
        ('pagadores', '0001_initial'),
        ('pagos', '0008_pago_concepto_libre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepto_alias', to=settings.AUTH_USER_MODEL)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concepto_alias', to='alumnos.alumno')),
                ('pagador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concepto_alias', to='pagadores.pagador')),
            ],
            options={
                'verbose_name': 'Alias de concepto',
                'verbose_name_plural': 'Alias de concepto',
                'ordering': ['alias_text'],
                'unique_together': {('academia', 'alias_text')},
            },
        ),
    ]
