# Generated by Django 6.0.4 on 2026-06-29 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_add_invoice_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('autonoma', models.CharField(max_length=200)),
                ('nif', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('factura_prefix', models.CharField(default='CC', max_length=10)),
                ('recibo_prefix', models.CharField(default='RE', max_length=10)),
                ('factura_baseline', models.IntegerField(default=0)),
                ('recibo_baseline', models.IntegerField(default=0)),
                ('drive_folder_id', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
