# Generated by Django 6.0.4 on 2026-07-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_documento_estado_anulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisor',
            name='recibo_efectivo_baseline',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emisor',
            name='recibo_efectivo_suffix',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('factura', 'Factura'), ('recibo', 'Recibo'), ('recibo_efectivo', 'Recibo (efectivo)'), ('otro', 'Otro')], max_length=20),
        ),
    ]
