# Generated by Django 6.0.4 on 2026-07-16 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_emisor_recibo_efectivo_baseline_and_more'),
        ('pagos', '0009_concepto_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='pagos.pago'),
        ),
    ]
