# Generated by Django 6.0.4 on 2026-09-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0009_documento_pdf_data"),
        ("pagos", "0009_concepto_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="pagos_adicionales",
            field=models.ManyToManyField(
                blank=True, related_name="documentos_combinados", to="pagos.pago"
            ),
        ),
    ]
