# Generated by Django 6.0.4 on 2026-10-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0010_documento_pagos_adicionales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("cuarentena", "En cuarentena"),
                    ("emitida", "Emitida"),
                    ("anulada", "Anulada"),
                    ("rectificada", "Rectificada"),
                ],
                default="borrador",
                max_length=20,
            ),
        ),
    ]
