# Generated by Django 6.0.4 on 2026-10-08 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0011_alter_documento_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="emisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentos",
                to="documentos.emisor",
            ),
        ),
    ]
