# Generated by Django 6.0.4 on 2026-05-07 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('empresas', '0002_alter_contactoempresa_id_alter_empresa_facturacion_and_more'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='grupos',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='aviso_cumple_dias',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fnac',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='es_fundae',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='grupos.grupo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nivel',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='AlumnoGrupo',
        ),
    ]
