# Generated by Django 6.0.4 on 2026-07-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_remove_alumno_grupos_remove_alumno_aviso_cumple_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='aviso_cumple_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
