# Generated by Django 6.0.4 on 2026-07-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_aviso_cumple_dias_alumno_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
