# Generated by Django 6.0.4 on 2026-07-23 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alumno_marca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='colegio_origen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='examen_objetivo',
            field=models.CharField(blank=True, choices=[('KET', 'KET'), ('PET', 'PET'), ('FCE', 'FCE'), ('CAE', 'CAE'), ('CPE', 'CPE'), ('ninguno', 'Ninguno')], max_length=10),
        ),
        migrations.AddField(
            model_name='alumno',
            name='foto_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='alumno',
            name='idioma_nativo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nivel_objetivo',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=5),
        ),
        migrations.CreateModel(
            name='ConsentimientoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('autorizacion_imagen', 'Autorización de imagen'), ('proteccion_datos', 'Protección de datos'), ('matricula', 'Matrícula')], max_length=25)),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('documento_url', models.CharField(blank=True, max_length=500)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='alumnos.alumno')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='DatoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True)),
                ('condiciones_medicas', models.TextField(blank=True)),
                ('medicacion', models.TextField(blank=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dato_salud', to='alumnos.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='FechaImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('examen', 'Examen'), ('revision_nivel', 'Revisión de nivel'), ('inicio_curso', 'Inicio de curso'), ('fin_curso', 'Fin de curso'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_importantes', to='alumnos.alumno')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='NotaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('progreso', 'Progreso'), ('reunion', 'Reunión'), ('general', 'General')], default='general', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_registro', to='alumnos.alumno')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_alumno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
