# Generated by Django 6.0.4 on 2026-08-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alumno_colegio_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='es_adulto',
            field=models.BooleanField(default=False),
        ),
    ]
