# Generated by Django 6.0.4 on 2026-08-24 20:23, hand-edited to preserve data:
# a student's existing single class assignment is copied into the new
# many-to-many table before the old column is dropped, instead of being
# silently lost (a student can now be in more than one class per week).

from django.db import migrations, models


def copy_grupo_to_grupos(apps, schema_editor):
    Alumno = apps.get_model("alumnos", "Alumno")
    for alumno in Alumno.objects.exclude(grupo__isnull=True).iterator():
        alumno.grupos.add(alumno.grupo_id)


def copy_grupos_back_to_grupo(apps, schema_editor):
    # Best-effort reverse: pick one membership (first by id) if any exist.
    Alumno = apps.get_model("alumnos", "Alumno")
    for alumno in Alumno.objects.prefetch_related("grupos").iterator():
        primero = alumno.grupos.order_by("id").first()
        if primero:
            alumno.grupo_id = primero.id
            alumno.save(update_fields=["grupo"])


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0007_alumno_es_adulto"),
        ("grupos", "0004_grupo_profesor"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="grupos",
            field=models.ManyToManyField(
                blank=True, related_name="alumnos", to="grupos.grupo"
            ),
        ),
        migrations.RunPython(copy_grupo_to_grupos, copy_grupos_back_to_grupo),
        migrations.RemoveField(
            model_name="alumno",
            name="grupo",
        ),
    ]
