# Generated by Django 6.0.4 on 2026-08-26 16:54, hand-edited to preserve
# data: existing (alumno, grupo) memberships are copied into the new
# Inscripcion rows (with hora_inicio/hora_fin left null = "full class
# session", matching current behavior) before the M2M switches over to using
# Inscripcion as its through table — otherwise every student would silently
# lose their class assignments.

import django.db.models.deletion
from django.db import migrations, models


def copiar_membresias_a_inscripcion(apps, schema_editor):
    Alumno = apps.get_model("alumnos", "Alumno")
    Inscripcion = apps.get_model("alumnos", "Inscripcion")
    # At this point in the migration, Alumno.grupos is still the OLD plain
    # M2M (the AlterField to `through=Inscripcion` hasn't run yet), so this
    # reads the old auto-generated join table.
    for alumno in Alumno.objects.prefetch_related("grupos"):
        for grupo in alumno.grupos.all():
            Inscripcion.objects.get_or_create(alumno=alumno, grupo=grupo)


def revertir_membresias(apps, schema_editor):
    # Reverse runs after AlterField's reverse, so Alumno.grupos is already
    # back to a plain M2M here — repopulate it from Inscripcion before that
    # model gets dropped by CreateModel's reverse.
    Alumno = apps.get_model("alumnos", "Alumno")
    for alumno in Alumno.objects.prefetch_related("inscripciones"):
        for insc in alumno.inscripciones.all():
            alumno.grupos.add(insc.grupo_id)


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0008_remove_alumno_grupo_alumno_grupos"),
        ("grupos", "0004_grupo_profesor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to="alumnos.alumno",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to="grupos.grupo",
                    ),
                ),
            ],
            options={
                "unique_together": {("alumno", "grupo")},
            },
        ),
        migrations.RunPython(copiar_membresias_a_inscripcion, revertir_membresias),
        # Django won't let AlterField add/remove `through=` on a M2M in
        # place — has to be a drop-and-recreate of the field itself. The
        # data migration above already preserved every membership in
        # Inscripcion before this runs, so nothing is lost.
        migrations.RemoveField(
            model_name="alumno",
            name="grupos",
        ),
        migrations.AddField(
            model_name="alumno",
            name="grupos",
            field=models.ManyToManyField(
                blank=True,
                related_name="alumnos",
                through="alumnos.Inscripcion",
                to="grupos.grupo",
            ),
        ),
    ]
