# Generated by Django 6.0.4 on 2026-09-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0013_alumno_ultimo_email_cumple_enviado"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="codigo_clase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HORA", "Clase grupo (1h/semana)"),
                    ("HORA_Y_MEDIA", "Clase grupo (1h30/semana)"),
                    ("PRIVADA", "Clase privada"),
                    ("PRIVADA_PROFESIONAL", "Clase privada profesional/adultos"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="alumno",
            name="cuota_manual",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
