# Generated by Django 6.0.4 on 2026-09-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0014_alumno_codigo_clase_alumno_cuota_manual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="codigo_clase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIVADA", "Clase privada"),
                    ("PRIVADA_PROFESIONAL", "Clase privada profesional/adultos"),
                ],
                max_length=20,
            ),
        ),
    ]
