# Generated by Django 6.0.4 on 2026-10-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0015_alter_alumno_codigo_clase"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="ranger_express",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alumno",
            name="recogida_colegio",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="alumno",
            name="recogida_dias",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="alumno",
            name="recogida_hora",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alumno",
            name="recogida_precio",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
        ),
    ]
