# Generated by Django 6.0.4 on 2026-07-04 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('clase_grupo', 'Clase Grupo'), ('bono_familia', 'Bono Familia'), ('clase_privada', 'Clase Privada'), ('clase_recuperada', 'Clase Recuperada')], max_length=20)),
                ('tipo_cobro', models.CharField(choices=[('por_hora', 'Por hora'), ('mensual', 'Mensual'), ('bono_familiar', 'Bono familiar')], max_length=20)),
                ('marca', models.CharField(choices=[('cami_and_co', 'Cami & Co'), ('rangers_academy', 'Rangers Academy')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('horas_semanales', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['marca', 'nombre', 'horas_semanales'],
            },
        ),
    ]
