# Generated by Django 6.0.4 on 2026-09-18 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0014_alumno_codigo_clase_alumno_cuota_manual"),
        ("tarifas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concepto", models.CharField(max_length=200)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=8)),
                ("fecha", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos_extra",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos_extra",
                        to="alumnos.alumno",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-created_at"],
            },
        ),
    ]
