# Generated by Django 6.0.4 on 2026-07-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_academia_owner_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marca_asignada',
            field=models.CharField(blank=True, choices=[('cami_and_co', 'Cami & Co'), ('rangers_academy', 'Rangers Academy')], max_length=20, null=True),
        ),
    ]
