# Generated by Django 6.0.4 on 2026-10-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_marca_asignada"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="modo_cuarentena",
            field=models.BooleanField(default=False),
        ),
    ]
