# Generated by Django 6.0.4 on 2026-08-18 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marca",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cami_and_co", "Cami & Co"),
                            ("rangers_academy", "Rangers Academy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("reunion", "Reunión"), ("feriado", "Feriado")],
                        max_length=10,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["fecha"],
            },
        ),
    ]
