# Generated by Django 6.0.4 on 2026-04-11 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nif', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('metodo', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('bizum', 'Bizum'), ('domiciliacion', 'Domiciliacion'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('frecuencia', models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('por_clase', 'Por clase'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=20)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('notas', models.TextField(blank=True)),
                ('fnac', models.DateField(blank=True, null=True)),
                ('aviso_cumple_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagadores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
