# Generated by Django 6.0.4 on 2026-08-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagador',
            name='direccion',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
