# Generated by Django 6.0.4 on 2026-04-11 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nivel', models.CharField(blank=True, max_length=50)),
                ('tarifa', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('aula', models.CharField(blank=True, max_length=100)),
                ('color_idx', models.PositiveSmallIntegerField(default=0)),
                ('horarios', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
