# Generated by Django 6.0.4 on 2026-05-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='precio_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='grupo',
            name='tipo_cobro',
            field=models.CharField(choices=[('mensual', 'Mensualidad fija'), ('por_hora', 'Por hora')], default='mensual', max_length=10),
        ),
    ]
