# Generated by Django 6.0.4 on 2026-07-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_grupo_precio_hora_grupo_tipo_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='marca',
            field=models.CharField(choices=[('cami_and_co', 'Cami & Co'), ('rangers_academy', 'Rangers Academy')], default='rangers_academy', max_length=20),
        ),
    ]
