# Generated by Django 6.0.4 on 2026-08-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grupos", "0003_grupo_marca"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="profesor",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
