# Generated by Django 6.0.4 on 2026-08-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grupos", "0003_grupo_marca"),
        ("profesores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="profesor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grupos",
                to="profesores.profesor",
            ),
        ),
    ]
